"use client"

import { createContext, useContext } from "react"

type Language = "en" | "hi"

interface LanguageContextType {
  language: Language
  toggleLanguage: () => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Landing Page
    for_street_food_vendors: "For Street Food Vendors",
    hero_title: "Connect with Verified Suppliers for Better Prices",
    hero_description:
      "Join thousands of street food vendors who save money by sourcing ingredients through our verified supplier network and group buying features.",
    start_selling: "Start Selling",
    become_supplier: "Become a Supplier",
    why_choose_us: "Why Choose VendorConnect?",
    features_description: "Everything you need to source ingredients at the best prices",
    verified_suppliers: "Verified Suppliers",
    verified_suppliers_desc: "All suppliers are verified for quality and reliability",
    group_buying: "Group Buying",
    group_buying_desc: "Join with other vendors to get bulk discounts",
    best_prices: "Best Prices",
    best_prices_desc: "Compare prices across suppliers to get the best deals",
    secure_payments: "Secure Payments",
    secure_payments_desc: "Safe and secure payment processing with UPI/Razorpay",
    ready_to_start: "Ready to Start Saving?",
    join_thousands: "Join thousands of vendors already saving money",
    get_started_free: "Get Started Free",
    all_rights_reserved: "All rights reserved.",

    // Auth
    back_to_home: "Back to Home",
    welcome: "Welcome to VendorConnect",
    auth_description: "Sign in to your account or create a new one",
    sign_in: "Sign In",
    sign_up: "Sign Up",
    email: "Email",
    password: "Password",
    signing_in: "Signing In...",
    user_type: "User Type",
    street_food_vendor: "Street Food Vendor",
    supplier: "Supplier",
    full_name: "Full Name",
    phone: "Phone Number",
    business_name: "Business Name",
    location: "Location",
    food_type: "Food Type",
    select_food_type: "Select food type",
    chaat: "Chaat",
    dosa: "Dosa",
    pav_bhaji: "Pav Bhaji",
    biryani: "Biryani",
    other: "Other",
    daily_requirements: "Daily Requirements",
    daily_requirements_placeholder: "Describe your daily ingredient needs...",
    company_name: "Company Name",
    business_address: "Business Address",
    supplier_type: "Supplier Type",
    select_supplier_type: "Select supplier type",
    vegetables: "Vegetables",
    spices: "Spices",
    oils: "Oils & Fats",
    grains: "Grains & Cereals",
    dairy: "Dairy Products",
    business_description: "Business Description",
    business_description_placeholder: "Tell us about your business...",
    creating_account: "Creating Account...",
    create_account: "Create Account",
    login: "Login",
    get_started: "Get Started",

    // Dashboard
    welcome_back: "Welcome back",
    vendor_dashboard_subtitle: "Manage your orders and find the best suppliers",
    supplier_dashboard_subtitle: "Manage your products and fulfill orders",
    total_orders: "Total Orders",
    active_groups: "Active Groups",
    total_savings: "Total Savings",
    low_stock_alerts: "Low Stock Alerts",
    from_last_month: "from last month",
    new_this_week: "new this week",
    items_need_reorder: "items need reorder",
    overview: "Overview",
    recent_orders: "Recent Orders",
    inventory_alerts: "Inventory Alerts",
    quick_actions: "Quick Actions",
    quick_actions_desc: "Common tasks and shortcuts",
    browse_suppliers: "Browse Suppliers",
    join_group_buying: "Join Group Buying",
    view_all_orders: "View All Orders",
    business_insights: "Business Insights",
    business_insights_desc: "Your business performance at a glance",
    avg_order_value: "Avg. Order Value",
    favorite_supplier: "Favorite Supplier",
    monthly_spending: "Monthly Spending",
    recent_orders_desc: "Your latest orders and their status",
    delivered: "Delivered",
    "in-transit": "In Transit",
    pending: "Pending",
    low_stock_desc: "Items running low that need reordering",
    current: "Current",
    reorder_at: "Reorder at",
    reorder_now: "Reorder Now",

    // Marketplace
    supplier_marketplace: "Supplier Marketplace",
    marketplace_subtitle: "Find verified suppliers for all your ingredient needs",
    search_suppliers: "Search suppliers or products...",
    category: "Category",
    all_categories: "All Categories",
    all_locations: "All Locations",
    verified: "Verified",
    products: "Products",
    more: "more",
    view_products: "View Products",
    no_suppliers_found: "No suppliers found",
    try_different_filters: "Try adjusting your search filters",

    // Group Buying
    group_buying_subtitle: "Save money by joining bulk purchase groups",
    create_group: "Create Group",
    my_groups: "My Groups",
    progress: "Progress",
    participants: "Participants",
    time_left: "Time Left",
    discount: "Discount",
    organized_by: "Organized by",
    join_group: "Join Group",
    savings: "Savings",
    completed: "Completed",
    view_details: "View Details",

    // Orders
    my_orders: "My Orders",
    orders_subtitle: "Track and manage all your orders",
    completed_orders: "Completed Orders",
    ordered_from: "Ordered from",
    delivery: "Delivery",
    items_ordered: "Items Ordered",
    tracking_info: "Tracking Information",
    tracking_id: "Tracking ID",
    supplier_contact: "Supplier Contact",
    delivery_address: "Delivery Address",
    cancel_order: "Cancel Order",
    contact_supplier: "Contact Supplier",
    no_active_orders: "No active orders",
    start_shopping_message: "Start shopping to see your orders here",
    delivered_on: "Delivered on",
    reorder: "Reorder",
    rate_supplier: "Rate Supplier",
    no_completed_orders: "No completed orders yet",
    completed_orders_message: "Your completed orders will appear here",

    // Admin
    access_denied: "Access Denied",
    admin_access_required: "Admin access required to view this page",
    admin_dashboard: "Admin Dashboard",
    admin_dashboard_subtitle: "Manage platform users and monitor activity",
    total_vendors: "Total Vendors",
    total_suppliers: "Total Suppliers",
    pending_verifications: "Pending Verifications",
    monthly_revenue: "Monthly Revenue",
    requires_attention: "requires attention",
    supplier_verification_requests: "Supplier Verification Requests",
    review_and_approve_suppliers: "Review and approve new supplier applications",
    supplier_name: "Supplier Name",
    company: "Company",
    type: "Type",
    registration_date: "Registration Date",
    actions: "Actions",
    review: "Review",
    approve: "Approve",
    reject: "Reject",
    no_pending_verifications: "No pending verifications",
    monitor_platform_activity: "Monitor recent platform activity",
    order_id: "Order ID",
    vendor: "Vendor",
    amount: "Amount",
    status: "Status",
    date: "Date",
    analytics: "Analytics",
    platform_growth: "Platform Growth",
    user_registration_trends: "User registration and growth trends",
    new_vendors_this_month: "New vendors this month",
    new_suppliers_this_month: "New suppliers this month",
    total_transactions: "Total transactions",
    popular_categories: "Popular Categories",
    most_ordered_items: "Most ordered item categories",

    // Navigation
    dashboard: "Dashboard",
    marketplace: "Marketplace",
    orders: "Orders",
    admin: "Admin",
    sign_out: "Sign Out",
  },
  hi: {
    // Landing Page
    for_street_food_vendors: "स्ट्रीट फूड विक्रेताओं के लिए",
    hero_title: "बेहतर कीमतों के लिए सत्यापित आपूर्तिकर्ताओं से जुड़ें",
    hero_description:
      "हजारों स्ट्रीट फूड विक्रेताओं से जुड़ें जो हमारे सत्यापित आपूर्तिकर्ता नेटवर्क और समूह खरीदारी सुविधाओं के माध्यम से सामग्री खरीदकर पैसे बचाते हैं।",
    start_selling: "बेचना शुरू करें",
    become_supplier: "आपूर्तिकर्ता बनें",
    why_choose_us: "VendorConnect क्यों चुनें?",
    features_description: "सबसे अच्छी कीमतों पर सामग्री खरीदने के लिए आपको जो कुछ भी चाहिए",
    verified_suppliers: "सत्यापित आपूर्तिकर्ता",
    verified_suppliers_desc: "सभी आपूर्तिकर्ता गुणवत्ता और विश्वसनीयता के लिए सत्यापित हैं",
    group_buying: "समूह खरीदारी",
    group_buying_desc: "थोक छूट पाने के लिए अन्य विक्रेताओं के साथ जुड़ें",
    best_prices: "सर्वोत्तम कीमतें",
    best_prices_desc: "सर्वोत्तम सौदे पाने के लिए आपूर्तिकर्ताओं की कीमतों की तुलना करें",
    secure_payments: "सुरक्षित भुगतान",
    secure_payments_desc: "UPI/Razorpay के साथ सुरक्षित भुगतान प्रसंस्करण",
    ready_to_start: "बचत शुरू करने के लिए तैयार हैं?",
    join_thousands: "पहले से ही पैसे बचाने वाले हजारों विक्रेताओं से जुड़ें",
    get_started_free: "मुफ्त में शुरू करें",
    all_rights_reserved: "सभी अधिकार सुरक्षित।",

    // Auth
    back_to_home: "होम पर वापस",
    welcome: "VendorConnect में आपका स्वागत है",
    auth_description: "अपने खाते में साइन इन करें या नया खाता बनाएं",
    sign_in: "साइन इन",
    sign_up: "साइन अप",
    email: "ईमेल",
    password: "पासवर्ड",
    signing_in: "साइन इन हो रहा है...",
    user_type: "उपयोगकर्ता प्रकार",
    street_food_vendor: "स्ट्रीट फूड विक्रेता",
    supplier: "आपूर्तिकर्ता",
    full_name: "पूरा नाम",
    phone: "फोन नंबर",
    business_name: "व्यापार का नाम",
    location: "स्थान",
    food_type: "भोजन का प्रकार",
    select_food_type: "भोजन का प्रकार चुनें",
    chaat: "चाट",
    dosa: "डोसा",
    pav_bhaji: "पाव भाजी",
    biryani: "बिरयानी",
    other: "अन्य",
    daily_requirements: "दैनिक आवश्यकताएं",
    daily_requirements_placeholder: "अपनी दैनिक सामग्री की जरूरतों का वर्णन करें...",
    company_name: "कंपनी का नाम",
    business_address: "व्यापारिक पता",
    supplier_type: "आपूर्तिकर्ता प्रकार",
    select_supplier_type: "आपूर्तिकर्ता प्रकार चुनें",
    vegetables: "सब्जियां",
    spices: "मसाले",
    oils: "तेल और वसा",
    grains: "अनाज और दालें",
    dairy: "डेयरी उत्पाद",
    business_description: "व्यापार विवरण",
    business_description_placeholder: "अपने व्यापार के बारे में बताएं...",
    creating_account: "खाता बनाया जा रहा है...",
    create_account: "खाता बनाएं",
    login: "लॉगिन",
    get_started: "शुरू करें",

    // Dashboard
    welcome_back: "वापस स्वागत है",
    vendor_dashboard_subtitle: "अपने ऑर्डर प्रबंधित करें और सर्वोत्तम आपूर्तिकर्ता खोजें",
    supplier_dashboard_subtitle: "अपने उत्पाद प्रबंधित करें और ऑर्डर पूरे करें",
    total_orders: "कुल ऑर्डर",
    active_groups: "सक्रिय समूह",
    total_savings: "कुल बचत",
    low_stock_alerts: "कम स्टॉक अलर्ट",
    from_last_month: "पिछले महीने से",
    new_this_week: "इस सप्ताह नए",
    items_need_reorder: "वस्तुओं को फिर से ऑर्डर करना है",
    overview: "अवलोकन",
    recent_orders: "हाल के ऑर्डर",
    inventory_alerts: "इन्वेंटरी अलर्ट",
    quick_actions: "त्वरित कार्य",
    quick_actions_desc: "सामान्य कार्य और शॉर्टकट",
    browse_suppliers: "आपूर्तिकर्ता ब्राउज़ करें",
    join_group_buying: "समूह खरीदारी में शामिल हों",
    view_all_orders: "सभी ऑर्डर देखें",
    business_insights: "व्यापारिक अंतर्दृष्टि",
    business_insights_desc: "एक नज़र में आपका व्यापारिक प्रदर्शन",
    avg_order_value: "औसत ऑर्डर मूल्य",
    favorite_supplier: "पसंदीदा आपूर्तिकर्ता",
    monthly_spending: "मासिक खर्च",
    recent_orders_desc: "आपके नवीनतम ऑर्डर और उनकी स्थिति",
    delivered: "डिलीवर किया गया",
    "in-transit": "ट्रांजिट में",
    pending: "लंबित",
    low_stock_desc: "कम चल रही वस्तुएं जिन्हें फिर से ऑर्डर करना है",
    current: "वर्तमान",
    reorder_at: "पर फिर से ऑर्डर करें",
    reorder_now: "अभी फिर से ऑर्डर करें",

    // Continue with other translations...
    supplier_marketplace: "आपूर्तिकर्ता बाज़ार",
    marketplace_subtitle: "अपनी सभी सामग्री आवश्यकताओं के लिए सत्यापित आपूर्तिकर्ता खोजें",
    search_suppliers: "आपूर्तिकर्ता या उत्पाद खोजें...",
    category: "श्रेणी",
    all_categories: "सभी श्रेणियां",
    all_locations: "सभी स्थान",
    verified: "सत्यापित",
    products: "उत्पाद",
    more: "और",
    view_products: "उत्पाद देखें",
    no_suppliers_found: "कोई आपूर्तिकर्ता नहीं मिला",
    try_different_filters: "अपने खोज फिल्टर को समायोजित करने का प्रयास करें",

    // Add more Hindi translations as needed...
    group_buying_subtitle: "थोक खरीदारी समूहों में शामिल होकर पैसे बचाएं",
    create_group: "समूह बनाएं",
    my_orders: "मेरे ऑर्डर",
    dashboard: "डैशबोर्ड",
    marketplace: "बाज़ार",
    orders: "ऑर्डर",
    admin: "एडमिन",
    sign_out: "साइन आउट",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

// This will be used in the provider
export { LanguageContext, translations }
